version: '3.9'

services:

  skillbox-msa-db:
    container_name: skillbox-msa-db
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - ../src/main/resources/data/postgres:/var/lib/postgresql/data
    ports:
      - "15432:5432"

