create user msa with password '123456' createdb;
create database users owner msa;

create table public.user
(
    ID         uuid unique default gen_random_uuid(),
    profile_id uuid not null
);

create table public.profile
(
    ID          uuid unique default gen_random_uuid(),
    "name"      varchar not null,
    surname     varchar not null,
    second_name varchar,
    birth_date  date    not null,
    avatar_link varchar,
    information text,
    city_id     smallint,
    contact_id  uuid    not null,
    gender_id      smallint
);

create table public.gender
(
    ID     smallint generated by default as identity primary key,
    "name" varchar not null unique
);

create table public.contact
(
    ID uuid unique default gen_random_uuid(),
    email varchar not null,
    phone varchar not null
);

create table public.city (
                             ID smallint generated by default as identity primary key,
                             "name" varchar not null
);

create table public.skill (
                              ID smallint generated by default as identity primary key,
                              "name" varchar
);

create table public.hard_skills (
                                    ID uuid unique default gen_random_uuid(),
                                    user_id uuid not null,
                                    skill_id smallint not null
);

create table public.subscription (
                                     ID uuid unique default gen_random_uuid(),
                                     subscriber_user_id uuid not null,
                                     subscribed_user_id uuid not null
);

alter table public.user add constraint user_profile_fk foreign key (profile_id) references public.profile(ID) on delete cascade on update cascade;

alter table public.profile add constraint profile_gender_fk foreign key (gender_id) references public.gender(ID) on delete no action on update no action;

alter table public.profile add constraint profile_contact_fk foreign key (contact_id) references public.contact(ID) on delete cascade on update cascade;

alter table public.profile add constraint profile_city_fk foreign key (city_id) references public.city(ID) on delete no action on update no action;

alter table public.hard_skills add constraint hard_skills_user_fk foreign key (user_id) references public.user(ID) on delete no action on update no action;

alter table public.hard_skills add constraint hard_skills_skill_fk foreign key (skill_id) references public.skill(ID) on delete no action on update no action;

alter table public.subscription add constraint subscription_subscriber_user_fk foreign key (subscriber_user_id) references public.user(ID) on delete no action on update no action;

alter table public.subscription add constraint subscription_subscribed_user_fk foreign key (subscribed_user_id) references public.user(ID) on delete no action on update no action;