version: '3.9'

services:

  skillbox-endpoint-db:
    container_name: skillbox-endpoint-db
    image: postgres:14.4
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
#    volumes:
#      - ../src/main/resources/data/postgres:/var/lib/postgresql/data
    ports:
      - "5433:5432"


