apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose.yml convert -c
    kompose.service.expose: "true"
    kompose.service.type: nodeport
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: skillbox-endpoint-db-helm
  name: skillbox-endpoint-db-helm
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: skillbox-endpoint-db-helm
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose -f docker-compose.yml convert -c
        kompose.service.expose: "true"
        kompose.service.type: nodeport
        kompose.version: 1.26.1 (a9d05d509)
      creationTimestamp: null
      labels:
        io.kompose.network/msa-net: "true"
        io.kompose.service: skillbox-endpoint-db-helm
    spec:
      containers:
        - env:
            - name: PGDATA
              value: /var/lib/postgresql/data
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: postgres:14.4
          name: skillbox-endpoint-db-helm
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
status: {}
