drop table if exists users_scheme.Companies cascade;
drop table if exists users_scheme.Addresses cascade;
drop table if exists users_scheme.Companies_addresses cascade;

create table users_scheme.user
(
    ID         uuid unique default gen_random_uuid(),
    profile_id uuid not null
);

create table users_scheme.profile
(
    ID          uuid unique default gen_random_uuid(),
    "name"      varchar not null,
    surname     varchar not null,
    second_name varchar,
    birth_date  date    not null,
    avatar_link varchar,
    information text,
    city_id     smallint,
    contact_id  uuid    not null,
    sex_id      smallint
);

create table users_scheme.sex
(
    ID     smallint generated by default as identity primary key,
    "name" varchar not null unique
);

create table users_scheme.contact
(
    ID uuid unique default gen_random_uuid(),
    email varchar not null,
    phone varchar not null
);

create table users_scheme.city (
                                   ID smallint generated by default as identity primary key,
                                   "name" varchar not null
);

create table users_scheme.skill (
                                    ID smallint generated by default as identity primary key,
                                    "name" varchar
);

create table users_scheme.hard_skills (
                                          ID uuid unique default gen_random_uuid(),
                                          user_id uuid not null,
                                          skill_id smallint not null
);

create table users_scheme.subscription (
                                           ID uuid unique default gen_random_uuid(),
                                           subscriber_user_id uuid not null,
                                           subscribed_user_id uuid not null
);

alter table users_scheme.user add constraint user_profile_fk foreign key (profile_id) references users_scheme.profile(ID) on delete cascade on update cascade;

alter table users_scheme.profile add constraint profile_sex_fk foreign key (sex_id) references users_scheme.sex(ID) on delete no action on update no action;

alter table users_scheme.profile add constraint profile_contact_fk foreign key (contact_id) references users_scheme.contact(ID) on delete cascade on update cascade;

alter table users_scheme.profile add constraint profile_city_fk foreign key (city_id) references users_scheme.city(ID) on delete no action on update no action;

alter table users_scheme.hard_skills add constraint hard_skills_user_fk foreign key (user_id) references users_scheme.user(ID) on delete no action on update no action;

alter table users_scheme.hard_skills add constraint hard_skills_skill_fk foreign key (skill_id) references users_scheme.skill(ID) on delete no action on update no action;

alter table users_scheme.subscription add constraint subscription_subscriber_user_fk foreign key (subscriber_user_id) references users_scheme.user(ID) on delete no action on update no action;

alter table users_scheme.subscription add constraint subscription_subscribed_user_fk foreign key (subscribed_user_id) references users_scheme.user(ID) on delete no action on update no action;